/**
 * THESE TYPES WILL BE REPLACED BY THE ONES GENERATED BY THE SERVER
 */
export enum ConnectionType {
    GoogleMeet = 'google_meet',
    PhoneNumber = 'phone',
    Webcast = 'webcast',
    Zoom = 'zoom',
}

export const CONNECTION_TYPE_OPTIONS = {
    [ConnectionType.Zoom]: {
        label: 'Zoom',
        value: ConnectionType.Zoom,
        description: 'Connect to a Zoom dial-in number',
    },
    [ConnectionType.GoogleMeet]: {
        label: 'Google Meet',
        value: ConnectionType.GoogleMeet,
        description: 'Connect to a Google Meet dial-in number',
    },
    [ConnectionType.Webcast]: {
        label: 'Webcast URL',
        value: ConnectionType.Webcast,
        description: 'Connect to a webcast url',
    },
    [ConnectionType.PhoneNumber]: {
        label: 'Phone Number',
        value: ConnectionType.PhoneNumber,
        description: 'Connect to any phone number, with optional pin',
    },
};
